export { About } from './About/About';
export { Career } from './Career/Career';
export { default as CareerId } from './CareerId/CareerId';
export { Contacts } from './Contacts/Contacts';
export { Home } from './Home/Home';
export { PageNotFound } from './PageNotFound/PageNotFound';
export { Portfolio } from './Portfolio/Portfolio';
export { PortfolioId } from './PortfolioId/PortfolioId';
export { Services } from './Services/Services';
export { ServicesOutsource } from './ServicesOutsource/ServicesOutsource';
export { ServicesOutstaff } from './ServicesOutstaff/ServicesOutstaff';
export { Team } from './Team/Team';
export { Testimonials } from './Testimonials/Testimonials';
